trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: kv-secrets

steps:

# Install Terraform
- script: |
    sudo apt-get update
    sudo apt-get install -y unzip wget
    wget https://releases.hashicorp.com/terraform/1.6.6/terraform_1.6.6_linux_amd64.zip
    unzip terraform_1.6.6_linux_amd64.zip
    sudo mv terraform /usr/local/bin/
    terraform version
  displayName: Install Terraform

# Terraform Init
- task: AzureCLI@2
  inputs:
    azureSubscription: 'azure-subscription-conn'
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      terraform init
  displayName: Terraform Init

# Terraform Plan
- task: AzureCLI@2
  inputs:
    azureSubscription: 'azure-subscription-conn'
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      terraform plan -var="vm_password=$(vm_password)"
  displayName: Terraform Plan

# Terraform Apply
- task: AzureCLI@2
  inputs:
    azureSubscription: 'azure-subscription-conn'
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      terraform apply -auto-approve -var="vm_password=$(vm_password)"
  displayName: Terraform Apply