trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
- group: kv-secrets

steps:

- task: TerraformInstaller@1
  inputs:
    terraformVersion: '1.6.6'

# INIT
- task: TerraformTaskV4@4
  displayName: "Terraform Init"
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'azure-subscription-conn'

# PLAN
- task: TerraformTaskV4@4
  displayName: "Terraform Plan"
  inputs:
    provider: 'azurerm'
    command: 'plan'
    environmentServiceNameAzureRM: 'azure-subscription-conn'
    commandOptions: '-var="vm_password=$(vm_password)"'

# APPLY
- task: TerraformTaskV4@4
  displayName: "Terraform Apply"
  inputs:
    provider: 'azurerm'
    command: 'apply'
    environmentServiceNameAzureRM: 'azure-subscription-conn'
    commandOptions: '-auto-approve -var="vm_password=$(vm_password)"'